exp:
  name: ${conf.dataset.obj_name}
  phase: train  # or val, test, predict
  predict_after_train: true
  test_after_train: true
  resume: false
  ckpt_path: ckpt
  exp_path: exp/lucesmv
  runs_dir: runs
  trial_name: null
  code_path: code
  save_dir: save
  config_path: configs
  tag: ""
  seed: 42

hydra:
  run:
    dir: ./
  output_subdir: null

trainer:
  max_steps: 20000
  log_every_n_steps: 100
  num_sanity_val_steps: 1
  val_check_interval: 1000
  limit_val_batches: 1
  limit_train_batches: 1.
  enable_progress_bar: true
  precision: 16

checkpoint:
  monitor: global_step
  mode: max
  save_top_k: 2
  every_n_train_steps: 5000
  save_last: true
  save_on_train_epoch_end: false
  filename: "{global_step}-{epoch}"

dataset:
  obj_name: Bowl
  root_dir: /projects/m25115/eval_3d_datasets/lucesmv/data
  data_dir: ${conf.dataset.root_dir}/${conf.dataset.obj_name}/mvps

  img_dirname: image
  img_ext: "png"
  img_load_fn: idr_img

  mask_dirname: mask
  mask_ext: "png"
  mask_load_fn: idr_mask

  normal_dirname: "None"
  normal_ext: "png"
  normal_load_fn: "None"

  camera_load_fn: idr_camera
  camera_select_fn: idr_camera_select

  cameras_fpath: ${conf.dataset.data_dir}/cameras.npz

  light_dir_file: "None"
  light_int_file: "None"
  sample_img_fname: "V00L00.png"
  sample_mask_fname: "V00.png"
  train:
    name: dataset_train
    init_num_rays_per_batch: 4096
    max_num_rays_per_batch: 4096
    img_downscale: 2 # 2080x1552 is large, downscale by 2
    view_light_index_fname: lucesmv_view_12_light_15
    view_light_index_file: ./configs/view_light_indices/${conf.dataset.train.view_light_index_fname}.txt

  val:
    name: dataset_val
    img_downscale: 2
    view_light_index_fname: lucesmv_view_12_light_15
    view_light_index_file: ./configs/view_light_indices/${conf.dataset.val.view_light_index_fname}.txt
    validataion_crop: true

  test:
    name: dataset_test
    img_downscale: 2
    img_mesh_downscale: 2
    gt_mesh_fpath: /projects/m25115/LucesMV/calibrated/${conf.dataset.obj_name}/${conf.dataset.obj_name}_gt.ply
    view_light_index_fname: lucesmv_view_12_light_15
    view_light_index_file: ./configs/view_light_indices/${conf.dataset.test.view_light_index_fname}.txt
    validataion_crop: true

  predict_targets: ["predict_brdf", "predict_relighting"]
  predict_mesh:
    dataset_name: mesh_export
    predict_step_fn_name: _predict_step_mesh
    gt_mesh_fpath: /projects/m25115/LucesMV/calibrated/${conf.dataset.obj_name}/${conf.dataset.obj_name}_gt.ply
    bbox_res: 512
    chunk_size: 2097152
    export_brdf_latent: false
    view_light_index_fname: lucesmv_view_12_light_15
    view_light_index_file: ./configs/view_light_indices/${conf.dataset.val.view_light_index_fname}.txt
    img_downscale: 2

  predict_brdf:
    dataset_name: brdf_render
    predict_step_fn_name: _predict_step_brdf
    img_downscale: 2
    brdf_sphere_res: 64
    view_light_index: "V00L00"
    light_direction: [0, 0, -1]

  predict_relighting:
    dataset_name: relighting
    predict_step_fn_name: _predict_step_relighting
    img_width: 512
    img_height: 512
    camera_focal_length_to_img_width_ratio: 5.0
    light_frames: 20
    light_elevation: 60
    camera_frames: 60
    camera_elevation: 10
    camera_distance: 8
    camera_lookat: [0, 0, 0]
    view_light_idx_sample: "V00L00"

model:
  name: mvscps
  radius: 1.0
  num_samples_per_ray: 1024
  num_lights: ${conf.dataset.train_num_lights}
  train_num_rays: 512
  max_train_num_rays: 4096
  grid_prune: true
  grid_prune_occ_thre: 0.1
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  cos_anneal_end: 5000
  save_mesh_interval: ${conf.trainer.max_steps}
  light:
    light_type: point                 # 'directional' or 'point'
    init_light_dir: [0, 0, -1.]
    init_light_pos: [0, 0, -1.0]
    init_intensity: 1.0
    use_gt_light: false
    freeze_light: false
    light_dir_file: "None"
    light_int_file: "None"
    light_pos_file: ${conf.dataset.data_dir}/light_positions_cam_scaled.npz
    attenuation_eps: 1.e-4
    view_light_index_fname_train: ${conf.dataset.train.view_light_index_file}
  variance:
    init_val: 0.3
    modulate: false
  geometry:
    name: neural_sdf
    radius: ${conf.model.radius}
    feature_dim: 64
    grad_type: analytic
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 14
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 32
      per_level_scale: 1.3195079107728942
      include_xyz: true
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
      sphere_init: true
      sphere_init_radius: 0.5
      weight_norm: true
  brdf:
    name: neural_brdf
    use_ae: true
    num_ae: 5
    input_feature_dim: ${add:${conf.model.geometry.feature_dim}, -1}
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 2
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: ReLU
      n_neurons: 64
      n_hidden_layers: 2
  shadow:
    name: shadow-mapping
    input_feature_dim: ${add:${conf.model.geometry.feature_dim}, -1}
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 3
    mlp_network_config:
      otype: VanillaMLP
      activation: ReLU
      output_activation: sigmoid
      n_neurons: 64
      n_hidden_layers: 2

system:
  name: mvscps
  loss:
    lambda_rgb_mse: 0.
    lambda_rgb_l1: 0.
    lambda_rgb_weighted_l1: 1.
    lambda_rgb_weighted_mse: 0.
    lambda_mask: 1.
    lambda_eikonal: 1.
  optimizer:
    name: AdamW
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.01
      brdf:
        lr: 0.01
      variance:
        lr: 0.001
      lighting:
        lr: 0.001
      shadow_mapping:
        lr: 0.001

  scheduler:
    name: SequentialLR
    constant_steps: 5000
    interval: step
    milestones:
      - ${conf.system.scheduler.constant_steps}
    schedulers:
      - name: ConstantLR
        args:
          factor: 1.0
          total_iters: ${conf.system.scheduler.constant_steps}
      - name: ExponentialLR
        args:
          gamma: ${calc_exp_lr_decay_rate:0.1,${sub:${conf.trainer.max_steps},${conf.system.scheduler.constant_steps}}}


export:
  chunk_size: 2097152
  export_spatial_latent: false
